pipeline {
  agent any

  tools{
    maven 'maven-3-6-1'
  }

  stages{
      stage("build"){
          steps{
              dir('java/cmad-ms-users/'){
                sh 'mvn compile'
              }
          }
      }
      stage("test"){
          steps{
              dir('java/cmad-ms-users/'){
                sh 'mvn clean test'
              }
          }
      }
      stage("package"){
          steps{
              dir('java/cmad-ms-users/'){
                sh 'mvn package -DskipTests'
              }
          }
      }
  }

  post{
    always{
        echo 'This pipeline is completed..'
    }
  }
}
