pipeline {
agent{
         docker{
           image ‘maven:3.6.1-jdk-8-slim’
           args ‘-v $HOME/.m2:/root/.m2’
         }
     }

  stages{
      stage("build"){
          steps{
              dir('java/cmad-ms-users/'){
                sh 'mvn compile'
              }
          }
      }
      stage("test"){
          steps{
              dir('java/cmad-ms-users/'){
                sh 'mvn clean test'
              }
          }
      }
      stage("package"){
          steps{
              dir('java/cmad-ms-users/'){
                sh 'mvn package -DskipTests'
                archiveArtifacts artifacts: 'java/cmad-ms-users/target/*.jar’, fingerprint: true
              }
          }
      }
  }

  post{
    always{
        echo 'This pipeline is completed..'
    }
  }
}
